import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { motion, AnimatePresence, springs } from '../components/ui';
import { safeOpenUrl } from '../utils/sanitize';
import { useToast } from '../contexts/ToastContext';
import { useUserProfile } from '../contexts/UserProfileContext';
import { closetCount, inCloset, onClosetChange, toggleCloset } from '../services/closet';
import {
  categoryToClothType,
  generateTryOnImage,
  TryOnAvatarMissingError,
  TryOnPollingCancelledError,
  type TryOnEngine,
  type TryOnQuality,
} from '../services/tryonService';

export type VTOState =
  | 'idle'
  | 'uploading'
  | 'processing'
  | 'rendering'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'timeout';

const SIZES = ['XS', 'S', 'M', 'L', 'XL'];

const FashionStudio: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { showToast } = useToast();
  const { userProfile } = useUserProfile();

  const [size, setSize] = useState('M');
  const [isZoomed, setIsZoomed] = useState(false);
  const [isAnimating, setIsAnimating] = useState(false);
  const [lighting, setLighting] = useState<'Studio' | 'Outdoor' | 'Night'>('Studio');
  const [isLiked, setIsLiked] = useState(false);
  const [toolsOpen, setToolsOpen] = useState(false);
  const [tryOnError, setTryOnError] = useState<string | null>(null);

  // Product Data from Location
  const incomingProduct = location.state?.product;
  const product = {
    id: incomingProduct?.id || 'wool-coat-1',
    name: incomingProduct?.title || 'Structured Wool Coat',
    brand: incomingProduct?.brand || 'The Row',
    price: incomingProduct?.price || '₹24,500',
    image: incomingProduct?.image || 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
    url: incomingProduct?.url || 'https://www.therow.com/',
    recommendedSize: incomingProduct?.recommendedSize || 'M',
  };

  // Try-On Generation
  const [tryonUrl, setTryonUrl] = useState<string | null>(null);
  const [tryonEngine, setTryonEngine] = useState<TryOnEngine | null>(null);
  const [vtoState, setVtoState] = useState<VTOState>('idle');
  const [vtoProgress, setVtoProgress] = useState(0);
  const [vtoStage, setVtoStage] = useState('Preparing look');
  const isGenerating = vtoState === 'uploading' || vtoState === 'processing' || vtoState === 'rendering';

  const autoGenerated = useRef(false);
  const tryOnAbortRef = useRef<AbortController | null>(null);
  const timeoutTimerRef = useRef<NodeJS.Timeout | null>(null);
  const mountedRef = useRef(true);
  const clothType = categoryToClothType(incomingProduct?.category);

  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
      tryOnAbortRef.current?.abort();
      if (timeoutTimerRef.current) {
        clearTimeout(timeoutTimerRef.current);
      }
    };
  }, []);

  const cancelTryOn = () => {
    if (tryOnAbortRef.current) {
      tryOnAbortRef.current.abort();
      tryOnAbortRef.current = null;
    }
    if (timeoutTimerRef.current) {
      clearTimeout(timeoutTimerRef.current);
      timeoutTimerRef.current = null;
    }
    setVtoState('cancelled');
    setTryOnError('Try-on cancelled by user.');
    showToast('Try-on cancelled', 'info');
  };

  const runTryOn = async (quality: TryOnQuality) => {
    if (isGenerating || !product.image || !mountedRef.current) return;
    tryOnAbortRef.current?.abort();
    if (timeoutTimerRef.current) {
      clearTimeout(timeoutTimerRef.current);
    }
    const controller = new AbortController();
    tryOnAbortRef.current = controller;

    setVtoState('uploading');
    setVtoProgress(5);
    setVtoStage('Preparing images');
    setTryOnError(null);

    // Timeout protection: abort after 45 seconds if the service hangs
    timeoutTimerRef.current = setTimeout(() => {
      if (tryOnAbortRef.current === controller) {
        controller.abort();
        tryOnAbortRef.current = null;
        if (mountedRef.current) {
          setVtoState('timeout');
          setTryOnError('Try-on request timed out after 45 seconds. The AI service may be busy.');
          showToast('Try-on request timed out. Please try again.', 'error');
        }
      }
    }, 45000);

    try {
      const result = await generateTryOnImage(
        {
          productImageUrl: product.image,
          clothType,
          quality,
          personImage: userProfile.photoURL || undefined,
        },
        (pct, stageDesc) => {
          if (!mountedRef.current || controller.signal.aborted) return;
          setVtoProgress(pct);
          if (stageDesc) setVtoStage(stageDesc);
          if (pct < 10) {
            setVtoState('uploading');
          } else if (pct < 35) {
            setVtoState('processing');
          } else {
            setVtoState('rendering');
          }
        },
        controller.signal,
      );
      if (controller.signal.aborted || !mountedRef.current) return;
      setVtoProgress(100);
      setVtoStage('Done');
      setVtoState('completed');
      setTryonUrl(result.imageUrl);
      setTryonEngine(result.engine);
    } catch (error: any) {
      if (error instanceof TryOnPollingCancelledError || controller.signal.aborted || !mountedRef.current) {
        if (vtoState !== 'timeout') {
          setVtoState('cancelled');
        }
        return;
      }
      if (error instanceof TryOnAvatarMissingError) {
        setVtoState('failed');
        setTryOnError('No avatar photo found. Please add your photo in Try-On Studio.');
        showToast('Upload your photo in the Try-On Studio', 'error');
        return;
      }
      console.error('Try-on generation failed:', error);
      setVtoState('failed');
      setTryOnError(error?.message || 'Try-on failed. Please try again.');
      showToast(error?.message || 'Try-on failed. Please try again.', 'error');
    } finally {
      if (timeoutTimerRef.current) {
        clearTimeout(timeoutTimerRef.current);
        timeoutTimerRef.current = null;
      }
      if (tryOnAbortRef.current === controller) {
        tryOnAbortRef.current = null;
      }
    }
  };

  useEffect(() => {
    if (autoGenerated.current) return;
    autoGenerated.current = true;
    runTryOn('fast');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Wishlist through the closet — instant local, Firestore-mirrored for real
  // accounts, and the Wishlist screen sees it either way.
  useEffect(() => {
    const sync = () => setIsLiked(inCloset('likes', product.id));
    sync();
    return onClosetChange(sync);
  }, [product.id]);

  const toggleWishlist = () => {
    toggleCloset('likes', {
      id: product.id, title: product.name, brand: product.brand,
      price: product.price, image: product.image, url: product.url,
    });
  };

  const changeSize = (newSize: string) => {
    if (newSize === size) return;
    setIsAnimating(true);
    setSize(newSize);
    setTimeout(() => setIsAnimating(false), 450);
  };

  // Gesture layer on the canvas: swipe = change size, double-tap = zoom.
  // Pointer-only, ref-tracked → no re-render, transform-only → 60fps.
  const gesture = useRef({ x: 0, t: 0, lastTap: 0 });
  const onCanvasDown = (e: React.PointerEvent) => {
    gesture.current.x = e.clientX;
    gesture.current.t = Date.now();
  };
  const onCanvasUp = (e: React.PointerEvent) => {
    const dx = e.clientX - gesture.current.x;
    const dt = Date.now() - gesture.current.t;
    if (Math.abs(dx) > 45 && dt < 600) {
      const i = SIZES.indexOf(size);
      const next = dx < 0 ? Math.min(i + 1, SIZES.length - 1) : Math.max(i - 1, 0);
      changeSize(SIZES[next]);
    } else if (Math.abs(dx) < 10 && dt < 300) {
      const now = Date.now();
      if (now - gesture.current.lastTap < 320) setIsZoomed(z => !z);
      gesture.current.lastTap = now;
    }
  };

  // Fit status — one source of truth, merged status + drape descriptor
  const fitFor = (s: string) => {
    const diff = SIZES.indexOf(s) - SIZES.indexOf(product.recommendedSize);
    if (diff === 0) return { text: 'Perfect fit', drape: 'natural fall', dot: '#5fce8f' };
    if (diff < 0) return { text: 'Tight fit', drape: 'structured', dot: '#f2705c' };
    return { text: 'Relaxed fit', drape: 'flowy drape', dot: '#e4b04d' };
  };
  const fit = fitFor(size);

  const lightingBg =
    lighting === 'Studio'
      ? 'radial-gradient(circle at center, #26211b 0%, #0b0906 100%)'
      : lighting === 'Outdoor'
        ? 'linear-gradient(to bottom, rgba(232,155,107,0.12), #0b0906)'
        : '#050403';

  const tools = [
    { key: 'light', label: lighting, icon: lighting === 'Studio' ? 'light_mode' : lighting === 'Outdoor' ? 'wb_cloudy' : 'dark_mode',
      onClick: () => setLighting(lighting === 'Studio' ? 'Outdoor' : lighting === 'Outdoor' ? 'Night' : 'Studio') },
    { key: 'zoom', label: isZoomed ? 'Zoom out' : 'Zoom in', icon: isZoomed ? 'zoom_out' : 'zoom_in',
      onClick: () => setIsZoomed(z => !z) },
    { key: 'max', label: 'Max quality', icon: 'auto_awesome', onClick: () => runTryOn('2k') },
    { key: 'live', label: 'Go live', icon: 'videocam',
      onClick: () => navigate('/live-tryon', { state: { product: incomingProduct || product } }) },
  ];

  return (
    <div className="relative h-screen h-dvh w-full text-white overflow-hidden select-none" style={{ background: 'linear-gradient(to bottom, #100d09, #1a1611)' }}>

      {/* ── HERO CANVAS ─────────────────────────────────────────────────
          The outfit is everything. Swipe = size, double-tap = zoom. */}
      <div
        className="absolute inset-0 touch-none"
        onPointerDown={onCanvasDown}
        onPointerUp={onCanvasUp}
        role="group"
        aria-label="Try-on preview. Swipe left or right to change size, double-tap to zoom."
      >
        <div className="absolute inset-0 transition-[background] duration-1000" style={{ background: lightingBg }} />
        <div className={`absolute inset-0 flex items-center justify-center transition-transform duration-700 ease-[cubic-bezier(0.22,1,0.36,1)] ${isZoomed ? 'scale-[1.28] translate-y-10' : 'scale-100'}`}>
          <div className={`relative h-full w-full max-w-lg transition-transform duration-500 ${isAnimating ? 'scale-[1.015]' : 'scale-100'}`}>
            <div className="absolute inset-0 animate-[breathe_5s_ease-in-out_infinite]">
              <img
                src={tryonUrl || product.image}
                decoding="async"
                className={`h-full w-full object-contain transition-[filter,opacity] duration-500 ${isGenerating ? 'blur-md opacity-30' : 'opacity-95'}`}
                alt={`${product.brand} ${product.name}, size ${size}`}
                style={{ maskImage: 'linear-gradient(to bottom, black 84%, transparent 100%)' }}
                referrerPolicy="no-referrer"
              />
            </div>
          </div>
        </div>

        {/* Cinematic render state — soft copper pulse + ring + progress + cancel */}
        <AnimatePresence>
          {isGenerating && (
            <motion.div
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="absolute inset-0 flex flex-col items-center justify-center gap-4 z-20"
            >
              <div className="relative flex items-center justify-center">
                <div className="absolute h-28 w-28 rounded-full bg-brand-on-media/20 blur-2xl animate-pulse" />
                <div className="h-14 w-14 rounded-full border-2 border-brand-on-media/30 border-t-brand-on-media animate-spin" />
                <span className="absolute text-[11px] font-bold text-brand-on-media">{vtoProgress}%</span>
              </div>
              <div className="flex flex-col items-center gap-1 text-center px-6">
                <span className="text-[11px] font-semibold uppercase tracking-[0.2em] text-brand-on-media">{vtoStage || 'Rendering your look'}</span>
                <span className="text-[10px] text-white/50">Quality: {lighting} · AI Fitting Engine</span>
              </div>
              <button
                type="button"
                onClick={(e) => { e.stopPropagation(); cancelTryOn(); }}
                className="mt-2 pointer-events-auto px-4 py-1.5 rounded-full bg-black/50 border border-white/20 text-white/80 hover:text-white hover:bg-black/70 text-[11px] font-medium transition-colors"
              >
                Cancel
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Engine provenance — quiet, top-left */}
        <AnimatePresence>
          {tryonEngine && !isGenerating && (
            <motion.div
              initial={{ opacity: 0, y: -6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
              className="absolute top-20 left-5 z-20 px-3 py-1 rounded-full bg-black/40 backdrop-blur-md border border-white/10"
            >
              <span className="text-[9px] font-semibold uppercase tracking-[0.16em] text-brand-on-media">
                AI Render
              </span>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Error / Timeout / Cancelled state overlay */}
        <AnimatePresence>
          {tryOnError && !isGenerating && (
            <motion.div
              initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }}
              className="absolute inset-x-6 bottom-32 z-30 p-5 rounded-2xl bg-surface-1/95 border border-line backdrop-blur-md shadow-float text-center flex flex-col items-center gap-3"
            >
              <div className="h-9 w-9 rounded-full bg-brand/10 text-brand flex items-center justify-center">
                <span className="material-symbols-outlined text-[20px]">
                  {vtoState === 'timeout' ? 'hourglass_top' : vtoState === 'cancelled' ? 'cancel' : 'info'}
                </span>
              </div>
              <div>
                <p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-brand mb-1">
                  {vtoState === 'timeout' ? 'Rendering Timed Out' : vtoState === 'cancelled' ? 'Try-On Cancelled' : 'Notice'}
                </p>
                <p className="text-[13px] text-ink-soft leading-relaxed">{tryOnError}</p>
              </div>
              <div className="flex gap-2 w-full pt-1">
                {tryOnError.toLowerCase().includes('avatar') ? (
                  <>
                    <button
                      type="button"
                      onClick={() => navigate(-1)}
                      className="flex-1 py-2 px-3 rounded-xl border border-line text-ink text-[12px] font-semibold"
                    >
                      Back
                    </button>
                    <button
                      type="button"
                      onClick={() => navigate('/tryon-studio', { state: { product: incomingProduct || product } })}
                      className="flex-1 py-2 px-3 rounded-xl bg-brand text-on-brand text-[12px] font-semibold shadow-sm"
                    >
                      Try-On Studio
                    </button>
                  </>
                ) : (
                  <>
                    <button
                      type="button"
                      onClick={() => setTryOnError(null)}
                      className="flex-1 py-2 px-3 rounded-xl border border-line text-ink text-[12px] font-semibold"
                    >
                      Dismiss
                    </button>
                    <button
                      type="button"
                      onClick={() => runTryOn('fast')}
                      className="flex-1 py-2 px-3 rounded-xl bg-brand text-on-brand text-[12px] font-semibold shadow-sm"
                    >
                      Try Again
                    </button>
                  </>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* ── TOP BAR — minimal: leave · share ───────────────────────────── */}
      <div className="absolute top-0 left-0 right-0 z-40 flex items-center justify-between px-5 py-4 pt-safe pointer-events-none">
        <button aria-label="Go back" onClick={() => navigate(-1)}
          className="pointer-events-auto h-10 w-10 flex items-center justify-center rounded-full bg-black/30 backdrop-blur-md border border-white/10 press-icon">
          <span className="material-symbols-outlined text-[18px] text-white" aria-hidden="true">arrow_back</span>
        </button>
        <button aria-label="Share this look"
          onClick={async () => {
            try {
              if (navigator.share) await navigator.share({ title: product.name, url: product.url });
              else { await navigator.clipboard.writeText(product.url); showToast('Link copied', 'success'); }
            } catch { /* user dismissed share sheet */ }
          }}
          className="pointer-events-auto h-10 w-10 flex items-center justify-center rounded-full bg-black/30 backdrop-blur-md border border-white/10 press-icon">
          <span className="material-symbols-outlined text-[18px] text-white" aria-hidden="true">ios_share</span>
        </button>
      </div>

      {/* ── CONTROL DOCK — the one surface the user acts on ─────────────── */}
      <motion.div
        initial={{ y: 48, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={springs.gentle}
        className="absolute bottom-0 left-0 right-0 z-40 px-4 pb-8 pb-safe"
      >
        {/* Fit pill — attached just above the dock. The text is keyed so it
            re-mounts and fades in on each size change (no AnimatePresence /
            mode="wait" — that leaks nodes when sizes change fast). */}
        <div className="flex justify-center mb-3">
          <div className="px-4 py-2 rounded-full bg-black/45 backdrop-blur-xl border border-white/10 flex items-center gap-2">
            <span className="h-2 w-2 rounded-full transition-colors duration-300" style={{ backgroundColor: fit.dot }} />
            <motion.span
              key={fit.text}
              initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
              className="flex items-center gap-2"
            >
              <span className="text-[11px] font-semibold uppercase tracking-[0.12em] text-white">{fit.text}</span>
              <span className="text-[11px] text-white/50 lowercase">· {fit.drape}</span>
            </motion.span>
          </div>
        </div>

        <div className="rounded-[1.75rem] bg-black/50 backdrop-blur-2xl border border-white/10 p-4 shadow-[0_-8px_40px_rgba(0,0,0,0.5)]">
          {/* Identity + size row */}
          <div className="flex items-end justify-between mb-3 px-1">
            <div className="min-w-0">
              <p className="text-[9px] font-semibold uppercase tracking-[0.18em] text-white/45">{product.brand}</p>
              <p className="text-[13px] text-white truncate">{product.name}</p>
            </div>
            <button
              onClick={() => setToolsOpen(o => !o)}
              aria-label="Adjust environment and quality"
              aria-expanded={toolsOpen}
              className="shrink-0 h-9 pl-3.5 pr-3 rounded-full border border-white/15 bg-white/5 flex items-center gap-1 text-white/70 press"
            >
              <span className="text-[10px] font-semibold uppercase tracking-[0.1em]">Adjust</span>
              <span className={`material-symbols-outlined text-[15px] transition-transform duration-300 ${toolsOpen ? 'rotate-180' : ''}`} aria-hidden="true">expand_more</span>
            </button>
          </div>

          {/* Size selector — swipe on canvas or tap here */}
          <div className="flex items-center justify-center gap-1.5 mb-1">
            {SIZES.map((s) => {
              const selected = size === s;
              const rec = s === product.recommendedSize;
              return (
                <button
                  key={s}
                  onClick={() => changeSize(s)}
                  aria-label={`Size ${s}${rec ? ', recommended' : ''}`}
                  aria-pressed={selected}
                  className={`relative h-11 flex-1 rounded-full flex items-center justify-center text-[14px] font-semibold transition-[background,color,transform] duration-300 ${
                    selected ? 'bg-white text-black' : 'text-white/55 bg-white/5 hover:bg-white/10'
                  } ${rec && !selected ? 'ring-1 ring-brand-on-media/60 text-brand-on-media' : ''}`}
                >
                  {s}
                  {rec && !selected && <span className="absolute -top-1 -right-1 h-2 w-2 rounded-full bg-brand-on-media" />}
                </button>
              );
            })}
          </div>
          {/* Stable gesture affordance — always teaches swipe (first-timers start
              on the recommended size, so this can't be gated on being off it) */}
          <p className="flex items-center justify-center gap-1.5 text-[10px] text-white/40 mb-3">
            <span className="material-symbols-outlined text-[13px]" aria-hidden="true">swipe</span>
            Swipe the photo or tap a size
          </p>

          {/* Expandable tools — lighting · zoom · max quality · live */}
          <AnimatePresence initial={false}>
            {toolsOpen && (
              <motion.div
                initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.28, ease: [0.22, 1, 0.36, 1] }}
                className="overflow-hidden"
              >
                <div className="grid grid-cols-4 gap-2 pb-3">
                  {tools.map(t => (
                    <button
                      key={t.key}
                      onClick={t.onClick}
                      disabled={t.key === 'max' && isGenerating}
                      aria-label={t.label}
                      className="flex flex-col items-center gap-1.5 py-2.5 rounded-2xl border border-white/10 bg-white/5 press disabled:opacity-40"
                    >
                      <span className="material-symbols-outlined text-[19px] text-white" aria-hidden="true">{t.icon}</span>
                      <span className="text-[9px] font-medium uppercase tracking-[0.08em] text-white/60">{t.label}</span>
                    </button>
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {/* Primary actions — Try again · Save · Buy */}
          <div className="flex items-center gap-2.5">
            <button
              onClick={() => runTryOn('fast')}
              disabled={isGenerating}
              aria-label="Try again"
              className="h-[52px] px-4 rounded-full border border-white/15 bg-white/5 flex items-center gap-2 text-white press disabled:opacity-40"
            >
              <span className={`material-symbols-outlined text-[19px] ${isGenerating ? 'animate-spin' : ''}`} aria-hidden="true">refresh</span>
              <span className="text-[11px] font-semibold uppercase tracking-[0.1em] hidden min-[380px]:inline">Try again</span>
            </button>
            <button
              onClick={toggleWishlist}
              aria-label={isLiked ? 'Saved to wishlist' : 'Save to wishlist'}
              aria-pressed={isLiked}
              className="h-[52px] w-[52px] shrink-0 rounded-full border border-white/15 bg-white/5 flex items-center justify-center press"
            >
              <span className={`material-symbols-outlined text-[21px] ${isLiked ? 'text-brand-on-media' : 'text-white'}`} style={{ fontVariationSettings: isLiked ? "'FILL' 1" : "'FILL' 0" }} aria-hidden="true">favorite</span>
            </button>
            <button
              onClick={() => safeOpenUrl(product.url)}
              aria-label={`Buy for ${product.price}`}
              className="h-[52px] flex-1 rounded-full bg-brand-on-media text-[#2a1608] flex items-center justify-center gap-2 press shadow-[0_6px_28px_rgba(232,155,107,0.4)]"
            >
              <span className="text-[12px] font-bold uppercase tracking-[0.12em]">Buy</span>
              <span className="text-[13px] font-bold opacity-80">{product.price}</span>
            </button>
          </div>

          {/* Continue — quiet */}
          <button onClick={() => navigate('/home')} className="w-full mt-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.14em] text-white/40 active:text-white/70 transition-colors">
            Explore more outfits
          </button>
        </div>
      </motion.div>

      <style>{`
        @keyframes breathe {
          0%, 100% { transform: scale(1); }
          50% { transform: scale(1.02); }
        }
      `}</style>
    </div>
  );
};

export default FashionStudio;
