import React, { useState, useEffect, useRef } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useToast } from '../contexts/ToastContext';
import { closetCount, inCloset, onClosetChange, toggleCloset } from '../services/closet';
import {
  categoryToClothType,
  generateTryOnImage,
  TryOnAvatarMissingError,
  type TryOnEngine,
  type TryOnQuality,
} from '../services/tryonService';

const FashionStudio: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { showToast } = useToast();

  // State
  const [size, setSize] = useState('M');
  const [isZoomed, setIsZoomed] = useState(false);
  const [isAnimating, setIsAnimating] = useState(false);
  const [lighting, setLighting] = useState<'Studio' | 'Outdoor' | 'Night'>('Studio');
  const [isLiked, setIsLiked] = useState(false);
  const [wishlistCount, setWishlistCount] = useState(0);

  // Product Data from Location
  const incomingProduct = location.state?.product;
  const product = {
    id: incomingProduct?.id || 'wool-coat-1',
    name: incomingProduct?.title || 'Structured Wool Coat',
    brand: incomingProduct?.brand || 'The Row',
    price: incomingProduct?.price || '₹24,500',
    image: incomingProduct?.image || 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000&auto=format&fit=crop',
    url: incomingProduct?.url || 'https://www.therow.com/',
    recommendedSize: incomingProduct?.recommendedSize || 'M'
  };

  const sizes = ['XS', 'S', 'M', 'L', 'XL'];

  // Try-On Generation
  const [tryonUrl, setTryonUrl] = useState<string | null>(null);
  const [tryonEngine, setTryonEngine] = useState<TryOnEngine | null>(null);
  const [generating, setGenerating] = useState(false);
  const autoGenerated = useRef(false);
  const clothType = categoryToClothType(incomingProduct?.category);

  const runTryOn = async (quality: TryOnQuality) => {
    if (generating || !product.image) return;
    setGenerating(true);
    try {
      const result = await generateTryOnImage({
        productImageUrl: product.image,
        clothType,
        quality,
      });
      setTryonUrl(result.imageUrl);
      setTryonEngine(result.engine);
      if (result.engine === 'overlay') {
        showToast('Quick preview shown — AI render unavailable right now, tap Try Again', 'success');
      }
    } catch (error: any) {
      if (error instanceof TryOnAvatarMissingError) {
        showToast('Upload your photo in the Try-On Studio', 'error');
        navigate('/tryon-studio', { state: { product: incomingProduct || product } });
        return;
      }
      console.error('Try-on generation failed:', error);
      showToast(error?.message || 'Try-on failed. Please try again.', 'error');
    } finally {
      setGenerating(false);
    }
  };

  useEffect(() => {
    if (autoGenerated.current) return;
    autoGenerated.current = true;
    runTryOn('fast');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Wishlist through the closet — instant for demo sessions, mirrored to
  // Firestore for signed-in users, and the Wishlist screen sees it either way.
  useEffect(() => {
    const sync = () => {
      setWishlistCount(closetCount('likes'));
      setIsLiked(inCloset('likes', product.id));
    };
    sync();
    return onClosetChange(sync);
  }, [product.id]);

  // The CTA flipping to "Saved" + the heart filling is the feedback — no toast.
  const toggleWishlist = () => {
    toggleCloset('likes', {
      id: product.id,
      title: product.name,
      brand: product.brand,
      price: product.price,
      image: product.image,
      url: product.url,
    });
  };

  // Handle Size Change Animation
  const handleSizeChange = (newSize: string) => {
    setIsAnimating(true);
    setSize(newSize);
    setTimeout(() => setIsAnimating(false), 500); // 500ms morph duration
  };

  // Fit Logic — semantic tones only (no hard-coded palette)
  const getFitStatus = () => {
    const indexDiff = sizes.indexOf(size) - sizes.indexOf(product.recommendedSize);
    if (indexDiff === 0) return { text: 'Perfect fit', dot: '#5fce8f' };
    if (indexDiff < 0) return { text: 'Tight fit', dot: '#f2705c' };
    return { text: 'Relaxed fit', dot: '#e4b04d' };
  };

  const fit = getFitStatus();

  // Warm atelier lighting environments — never blue
  const lightingBg =
    lighting === 'Studio'
      ? 'radial-gradient(circle at center, #26211b 0%, #0b0906 100%)'
      : lighting === 'Outdoor'
        ? 'linear-gradient(to bottom, rgba(232,155,107,0.12), #0b0906)'
        : '#050403';

  return (
    <div className="relative h-screen h-dvh w-full text-white overflow-hidden select-none" style={{ background: 'linear-gradient(to bottom, #100d09, #1a1611)' }}>

      {/* Top Minimal Navbar */}
      <div className="absolute top-0 left-0 right-0 z-50 flex items-center justify-between px-5 py-4 pt-safe bg-black/30 backdrop-blur-md border-b border-white/5">
        <button aria-label="Go back"
          onClick={() => navigate(-1)}
          className="h-10 w-10 flex items-center justify-center rounded-full border border-white/10 press-icon"
        >
          <span className="material-symbols-outlined text-[18px] text-white" aria-hidden="true">arrow_back</span>
        </button>

        <div className="flex flex-col items-center">
          <span className="text-[9px] font-semibold uppercase tracking-[0.2em] text-white/45">{product.brand}</span>
          <span className="font-display text-[15px] leading-none text-white mt-0.5">
            <span className="italic font-light">Zip</span><span className="font-semibold">RIGHT</span>
            <span className="text-white/40 mx-1.5 font-sans text-[11px]">/</span>
            <span className="text-[11px] font-sans font-semibold uppercase tracking-[0.14em] align-middle">Studio</span>
          </span>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={toggleWishlist}
            aria-label="Toggle wishlist"
            className="h-10 w-10 flex items-center justify-center rounded-full border border-white/10 press-icon relative"
          >
            <span className={`material-symbols-outlined text-[18px] ${isLiked ? 'text-brand-on-media' : 'text-white'}`} style={{ fontVariationSettings: isLiked ? "'FILL' 1" : "'FILL' 0" }} aria-hidden="true">favorite</span>
            {wishlistCount > 0 && (
              <span className="absolute -top-1 -right-1 h-4 w-4 rounded-full text-[9px] font-bold flex items-center justify-center text-black bg-brand-on-media">
                {wishlistCount}
              </span>
            )}
          </button>
          <button aria-label="Share" onClick={() => { if (navigator.share) navigator.share({ title: product.name, url: product.url }).catch(() => {}); }} className="h-10 w-10 flex items-center justify-center rounded-full border border-white/10 press-icon">
            <span className="material-symbols-outlined text-[18px] text-white" aria-hidden="true">ios_share</span>
          </button>
        </div>
      </div>

      {/* Fullscreen Try-On Canvas */}
      <div className={`relative w-full h-[85vh] mt-[8vh] transition-all duration-700 ease-in-out ${isZoomed ? 'scale-125 translate-y-10' : 'scale-100'}`}>

        {/* Background Environment / Lighting */}
        <div className="absolute inset-0 transition-all duration-1000" style={{ background: lightingBg }}></div>

        {/* Avatar Layer */}
        <div className="absolute inset-0 flex items-center justify-center">
          <div className={`relative h-full w-full max-w-lg transition-transform duration-500 ${isAnimating ? 'scale-[1.01]' : 'scale-100'}`}>
            <div className="absolute inset-0 animate-[breathe_4s_ease-in-out_infinite]">
              <img
                src={tryonUrl || product.image}
                className={`h-full w-full object-contain transition-all duration-500 ${generating ? 'blur-sm opacity-40' : 'opacity-90'}`}
                alt="Virtual Try On"
                style={{ maskImage: 'linear-gradient(to bottom, black 85%, transparent 100%)' }}
                referrerPolicy="no-referrer"
              />
              {generating && (
                <div className="absolute inset-0 flex flex-col items-center justify-center gap-3 z-10">
                  <div className="h-12 w-12 rounded-full border-2 border-brand-on-media border-t-transparent animate-spin"></div>
                  <span className="text-[10px] font-semibold uppercase tracking-[0.14em] text-brand-on-media">Rendering your look</span>
                </div>
              )}
              {tryonEngine && !generating && (
                <div className="absolute top-3 left-3 z-10 px-3 py-1 rounded-full bg-black/50 backdrop-blur-md border border-white/10">
                  <span className="text-[9px] font-semibold uppercase tracking-[0.14em] text-brand-on-media">
                    {tryonEngine === 'overlay' ? 'Preview' : 'AI Render'}
                  </span>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Fit Status Micro Badge */}
        <div className="absolute top-[10%] right-[12%] z-20">
          <div className="px-3 py-1.5 rounded-full bg-black/40 backdrop-blur-md border border-white/10 flex items-center gap-2">
            <div className="h-1.5 w-1.5 rounded-full" style={{ backgroundColor: fit.dot }}></div>
            <span className="text-[10px] font-semibold uppercase tracking-[0.1em] text-white">{fit.text}</span>
          </div>
        </div>

      </div>

      {/* Try-On Controls + Heatmap Toggle (Left Float) */}
      <div className="absolute left-5 bottom-32 z-30 flex flex-col gap-3.5 items-center">
        <button
          onClick={() => runTryOn('fast')}
          disabled={generating}
          aria-label="Try again"
          className="h-11 w-11 rounded-full flex items-center justify-center border border-white/15 bg-black/30 text-brand-on-media backdrop-blur-md press-icon disabled:opacity-40"
        >
          <span className={`material-symbols-outlined text-[19px] ${generating ? 'animate-spin' : ''}`} aria-hidden="true">refresh</span>
        </button>
        <button
          onClick={() => runTryOn('2k')}
          disabled={generating}
          aria-label="Best quality render"
          className="h-11 w-11 rounded-full flex items-center justify-center border border-white/15 bg-black/30 text-brand-on-media backdrop-blur-md press-icon disabled:opacity-40"
        >
          <span className="text-[10px] font-bold tracking-wide">MAX</span>
        </button>
        <button
          onClick={() => navigate('/live-tryon', { state: { product: incomingProduct || product } })}
          aria-label="Live try-on"
          className="h-11 w-11 rounded-full flex items-center justify-center border border-white/15 bg-black/30 text-brand-on-media backdrop-blur-md press-icon"
        >
          <span className="material-symbols-outlined text-[19px]" aria-hidden="true">videocam</span>
        </button>
      </div>

      {/* View Controls (Right Float) */}
      <div className="absolute right-5 bottom-32 z-30 flex flex-col gap-2.5 items-center">
        <button
          onClick={() => setIsZoomed(!isZoomed)}
          aria-label={isZoomed ? 'Zoom out' : 'Zoom in'}
          className={`h-10 w-10 rounded-full flex items-center justify-center border transition-all backdrop-blur-md ${isZoomed ? 'bg-white text-black border-white' : 'bg-black/30 border-white/15 text-white/60'}`}
        >
          <span className="material-symbols-outlined text-[18px]" aria-hidden="true">{isZoomed ? 'zoom_out' : 'zoom_in'}</span>
        </button>
        <div className="h-px w-5 bg-white/10 my-0.5"></div>
        <button
          onClick={() => setLighting(lighting === 'Studio' ? 'Outdoor' : lighting === 'Outdoor' ? 'Night' : 'Studio')}
          aria-label="Cycle lighting"
          className="h-10 w-10 rounded-full flex items-center justify-center border border-white/15 bg-black/30 text-white/60 backdrop-blur-md press-icon"
        >
          <span className="material-symbols-outlined text-[18px]" aria-hidden="true">{lighting === 'Studio' ? 'light_mode' : lighting === 'Outdoor' ? 'wb_cloudy' : 'dark_mode'}</span>
        </button>
      </div>

      {/* Size Switcher (Bottom Float Dock) */}
      <div className="absolute bottom-[104px] left-0 right-0 flex flex-col items-center gap-3 z-40">
        <div className="flex items-center gap-2 opacity-80">
          <span className="material-symbols-outlined text-[13px] text-brand-on-media" aria-hidden="true">accessibility</span>
          <span className="text-[10px] font-semibold uppercase tracking-[0.12em] text-white/70">
            {size === 'XS' || size === 'S' ? 'Structured fit' : size === 'XL' ? 'Flowy drape' : 'Natural fall'}
          </span>
        </div>

        <div className="flex items-center gap-1.5 p-1.5 bg-black/40 backdrop-blur-xl border border-white/10 rounded-full">
          {sizes.map((s) => {
            const isSelected = size === s;
            const isRecommended = s === product.recommendedSize;

            return (
              <button
                key={s}
                onClick={() => handleSizeChange(s)}
                aria-label={`Size ${s}${isRecommended ? ' (recommended)' : ''}`}
                aria-pressed={isSelected}
                className={`relative h-9 w-9 rounded-full flex items-center justify-center text-[13px] font-semibold transition-all duration-300 ${
                  isSelected
                    ? 'bg-white text-black scale-110'
                    : 'text-white/50 hover:text-white hover:bg-white/5'
                } ${isRecommended && !isSelected ? 'border border-brand-on-media/60 text-brand-on-media' : ''}`}
              >
                {s}
                {isRecommended && !isSelected && (
                  <div className="absolute -top-1 -right-1 h-2 w-2 bg-brand-on-media rounded-full"></div>
                )}
              </button>
            );
          })}
        </div>
      </div>

      {/* Bottom Actions */}
      <div className="absolute bottom-0 left-0 right-0 z-50 p-6 pb-8 pb-safe bg-gradient-to-t from-[#100d09] via-[#100d09]/85 to-transparent">
        <div className="flex flex-col gap-3 max-w-md mx-auto">
          <button
            onClick={toggleWishlist}
            className="w-full h-[54px] rounded-full bg-[#f1ede3] text-[#14120f] font-semibold text-[12px] uppercase tracking-[0.12em] press flex items-center justify-center gap-2"
          >
            {isLiked ? 'Saved to wishlist' : 'Add to wishlist'}
            <span className="material-symbols-outlined text-[16px]" style={{ fontVariationSettings: isLiked ? "'FILL' 1" : "'FILL' 0" }} aria-hidden="true">favorite</span>
          </button>
          <button
            onClick={() => navigate('/home')}
            className="w-full h-12 rounded-full border border-white/15 text-white/70 font-semibold text-[11px] uppercase tracking-[0.12em] press"
          >
            Explore more outfits
          </button>
        </div>
      </div>

      {/* Global Styles for Animations */}
      <style>{`
        @keyframes breathe {
            0%, 100% { transform: scale(1); }
            50% { transform: scale(1.02); }
        }
      `}</style>

    </div>
  );
};

export default FashionStudio;
